### ISSUE TITLE
Alternative locale not working

### ISSUE THREAD

**Issue by philitell** [tomasweigenast/paged-datatable#24] opened 2024-06-06 07:41 UTC
Maybe i am doing something wrong but when i'm changing the locale to "es" or "de" it seems to have no effect.
E.g. the datePicker-widget uses the correct locale but the menu-items in the header- and footer section of PagedDataTable remain using english-locale (i'm not using a custom header or footer widget).

In my case the only supported locale is "de", but all PagedDataTable-Widgets are in english.

```
      localizationsDelegates: const [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        FormBuilderLocalizations.delegate,
        PagedDataTableLocalization.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
```

**Comment by tomasweigenast** [comment] 2024-06-07 00:32
I was not able to reproduce the issue. I tested the example project with every locale and it works. Can you provide a reproducible example?

**Comment by philitell** [comment] 2024-06-10 11:43
I've done more testing - it seems only the german locale is not working.
"en", "es" and "it" are working when i force flutter to use a specific locale for the PagedDataTableWidget. When i'm using "de" it shows english text.

```
            child: Localizations.override(
              context: context,
              locale: const Locale("de"),
              child: PagedDataTable<String, FullFeedback>(
                controller: tableController,
                initialPage: "0",
                initialPageSize: 20,
                pageSizes: const [20, 50],
                fetcher: (int pageSize, SortModel? sortModel, FilterModel filterModel, String? pageToken) async {
                  int offset = int.tryParse(pageToken ?? "0") ?? 0;
                 ....
```


I'm trying to provide a reproducible example

**Comment by tomasweigenast** [comment] 2024-06-10 11:46
> I'm trying to provide a reproducible example
Yes, please, because I tried every supported language and they work.

**Comment by philitell** [comment] 2024-06-10 13:14
Ok i tested all languages with the counter-app and all languages work. BUT when i'm running a project that uses flutter_intl -plugin (https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl), then there is somehow a conflict within the delegates PagedDataTableLocalization.delegate and S.delegate.

The order in "localizationDelegates" seems to matter.
When i'm using:
```
localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        FormBuilderLocalizations.delegate,
        PagedDataTableLocalization.delegate,
        S.delegate,
      ],
```
Then all translations from PagedDataTableLocalization are working but the ones from S.delegate won't.
It is the other way round when i'm using:
```
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        FormBuilderLocalizations.delegate,
        S.delegate,
        PagedDataTableLocalization.delegate,
      ],
```
This seem to be a package-specific issue because "FormBuilderLocalizations.delegate" which comes from the package "form_builder_validators" is not affected by all of this. It works fine not matter what order is used.

**Comment by philitell** [comment] 2024-06-10 13:16
Here is the example:
```
import 'package:flutter/material.dart';
import "package:flutter_localizations/flutter_localizations.dart";
import 'package:form_builder_validators/localization/l10n.dart';
import 'package:paged_datatable/l10n/generated/l10n.dart';

import 'generated/l10n.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        PagedDataTableLocalization.delegate,
        S.delegate,
        FormBuilderLocalizations.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    const String overriddenLocale = "de";
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(S.of(context).language),
            Text(PagedDataTableLocalization.of(context).nextPageButtonText),
            Localizations.override(
                context: context,
                // NOTE: if you change this line to "en", "it" or "es" then the text is shown in the correct language
                // "de" is not working
                locale: const Locale(overriddenLocale),
                child: Builder(builder: (context) {
                  return Column(
                    children: [
                      const SizedBox(
                        height: 50,
                      ),
                      const Text("With overridden context and locale set to: $overriddenLocale"),
                      Text(S.of(context).language),
                      Text(PagedDataTableLocalization.of(context).nextPageButtonText),
                      Text(FormBuilderLocalizations.of(context).emailErrorText),
                    ],
                  );
                })),
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

pubspec.yaml
```
name: paged_data_table_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  paged_datatable: ^2.1.0
  intl: any
  form_builder_validators: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  default_locale: de
```

I have added locale "de" and "en" with flutter_intl-plugin

**Comment by philitell** [comment] 2024-06-10 13:21
The problem might be that intl’s initializeMessages can only be called once per locale. But other packages seem to handle this issue. I have used flutter_intl-plugin in many projects alongside localication-delegates from other packages - and i never had any issues.

**Comment by tomasweigenast** [comment] 2024-06-10 18:40
Please, provide a link to a repository that I can clone to reproduce the issue. If you also can list the packages that handle the issue I would be grateful

**Comment by philitell** [comment] 2024-06-11 06:06
Here is the code-example: https://github.com/philitell/paged_data_table_test

A package that handles this issue well: https://pub.dev/packages/form_builder_validators

Issue related links:
https://stackoverflow.com/questions/57267141/use-multiple-localizationsdelegates-in-flutter
https://github.com/dart-lang/i18n/issues/358
https://github.com/Innim/flutter_multiple_localization

**Comment by tomasweigenast** [comment] 2024-07-14 13:31
I will close this because I could not reproduce the issue. Feel free to re-open if you continue having this error after testing the new version I'll release in a few hours.

**Closed by tomasweigenast** 2024-07-14 13:31 UTC
